package walletmanager.exception;

public enum ErrorCode
{
    ACCOUNT_NOT_FOUND,
    ACCOUNT_DATA_INVALID,
    USER_NOT_FOUND,
    USER_DATA_INVALID,
    TRANSACTION_DATA_INVALID,
    INSUFFICIENT_FUNDS,
    ILLEGAL_TRANSACTION,
    CONCURRENT_TRANSACTION,
    CURRENCY_MISMATCH
}